### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by kevindiffily** [cilix-lab/docker-netatalk#3]
Get above error after running docker run -it -p 548:548 cilix/netatalk -s "Shared;/shares".
Running on Raspberry Pi 3B+

uname -a
Linux homeautomation2 4.19.27-v7+ #1206 SMP Wed Mar 6 14:40:18 GMT 2019 armv7l GNU/Linux

**Comment by tomieq** [comment]
Any solution to this problem? I'm having exactly the same issue on Raspberry.

**Comment by cilix-lab** [comment]
I am no longer maintaining this repository. I'm guessing the issue has to do with the RPi architecture, since this was conceived to be used on `x86-64` and the RPi is `arm`.

BTW, if you're looking into having shares on your network that are Mac friendly, I think Apple moved away from AFP in favor of SMB. I myself have Time Machine running on SMB. You just need to add some extra flags in the config.
